#!/usr/bin/env python3
"""Generate a backend-portable copy of a gpu/ spiral driver.

    python3 portable/port_driver.py            # regenerate every driver
    python3 portable/port_driver.py spiral_f_perf.jl

Only the mappings in PortableBackend.jl's table are applied; gates, inputs,
host math and CSV rows are left byte-for-byte as the original wrote them. The
local device-kernel definitions are dropped because TetKernels holds verbatim
ports (proven bit-identical by parity.jl). The script refuses to write a file
if any CUDA-specific call survives outside a comment.
"""
import re
import sys
from pathlib import Path

LAB = Path(__file__).resolve().parent.parent
DRIVERS = [
    "spiral_e_gpu.jl",
    "spiral_f_perf.jl",
    "spiral_h_fusion.jl",
    "spiral_h2_wind_ladder.jl",
    "spiral_i_comparators.jl",
]

# asserts that test a performance hypothesis, not correctness (by gate id)
SOFT_GATES = ["HF-G3 FAILED", "HF-G4′ sanity FAILED", "F-G2 FAILED"]

HEADER = """#
# PORTABLE COPY, generated by portable/port_driver.py from gpu/{src}.
# Do not edit by hand: change the original or the generator. Backend calls go
# through PortableBackend; kernels come from TetKernels.
#   julia --project=portable portable/{dst} cuda|rocm|cpu
include("PortableBackend.jl"); using .PortableBackend
include("TetKernels.jl"); using .TetKernels
"""


def drop_device_kernels(s):
    """Remove top-level `function ... end` blocks whose body uses blockIdx."""
    out, lines, i = [], s.split("\n"), 0
    while i < len(lines):
        if re.match(r"^function \w+!?\(", lines[i]):
            j = i
            while lines[j] != "end":
                j += 1
            block = "\n".join(lines[i : j + 1])
            if "blockIdx" in block:
                name = re.match(r"^function (\w+!?)", lines[i]).group(1)
                out.append(f"# {name}: TetKernels.{name} (verbatim port)")
                i = j + 1
                if i < len(lines) and lines[i] == "":
                    i += 1
                continue
        out.append(lines[i])
        i += 1
    return "\n".join(out)


def port(src_name):
    stem = src_name[: -len(".jl")]
    dst_name = stem + "_portable.jl"
    s = (LAB / "gpu" / src_name).read_text()

    s = s.replace("using CUDA\n", HEADER.format(src=src_name, dst=dst_name), 1)
    s = drop_device_kernels(s)

    # device notes: the first CUDA device line becomes the backend's notes
    s, n = re.subn(r'push!\(notes, "device: \$\(CUDA\.name\(CUDA\.device\(\)\)\)[^\n]*\)\n',
                   "append!(notes, device_notes())\n", s, count=1)
    assert n == 1, "device note not found"
    s = re.sub(r'push!\(notes, "cuda runtime: \$\(CUDA\.runtime_version\(\)\)"\)\n', "", s)

    # graphs first, so the plain `launch(` rewrite below cannot touch them
    s = re.sub(r"\bcapture\(", "graph_capture(", s)
    s = re.sub(r"\binstantiate\(", "graph_instantiate(", s)
    s = re.sub(r"-> launch\(", "-> graph_launch(", s)

    # @cuda threads=T blocks=cld(N, T) k!(args...)  ->  launch(k!, N, args...)
    s = re.sub(r"@cuda threads=\w+ blocks=cld\(([^,]+), \w+\) (\w+!)\(", r"launch(\2, \1, ", s)
    s = s.replace("CUDA.synchronize()", "sync!()")
    s = re.sub(r"CUDA\.@elapsed (\w+!?)\(\)", r"gpu_elapsed(\1)", s)
    s = s.replace("CUDA.pin(", "pin_host(")
    s = s.replace("CUDA.zeros(", "devzeros(")
    s = re.sub(r"\bCuArray\(", "todev(", s)

    # performance hypotheses become recorded verdicts (see PortableBackend.soft_gate)
    for gate in SOFT_GATES:
        s, n = re.subn(r'@assert (.+?) "(' + re.escape(gate) + r'[^"]*)"', r'soft_gate(\1, "\2")', s)
        assert n <= 1, f"{gate}: expected at most one assert, found {n}"
    if "soft_gate(" in s:
        s, n = re.subn(r'\ntext = "# Spiral', '\nappend!(notes, soft_gate_notes())\ntext = "# Spiral', s, count=1)
        assert n == 1, "could not place soft-gate notes before the report text"
        s = s.rstrip("\n") + "\nreport_soft_gates()\n"

    # outputs: name the backend in the title and write beside, never over, the original
    s = re.sub(r'(text = "# Spiral [^\n]*?)RTX 5060[^)\n]*', r"\1portable driver, backend $BACKEND_NAME", s)
    s = re.sub(r'joinpath\(resdir, "([^"]+)\.csv"\)', r'joinpath(resdir, "\1-portable-$BACKEND_NAME.csv")', s)

    leftovers = []
    string_lit = r'"(?:[^"\\]|\\.)*"'
    for k, line in enumerate(s.split("\n"), 1):
        if line.lstrip().startswith("#"):
            continue
        strings = " ".join(re.findall(string_lit, line))
        code = re.sub(string_lit, '""', line).split("#", 1)[0]
        if re.search(r"CUDA\.|@cuda|\bCuArray\b", code) or "RTX 5060" in strings:
            leftovers.append(f"  {dst_name}:{k}: {line.strip()}")
    if leftovers:
        sys.exit("CUDA-specific code left after porting:\n" + "\n".join(leftovers))

    (LAB / "portable" / dst_name).write_text(s)
    print(f"wrote portable/{dst_name}")


if __name__ == "__main__":
    for name in sys.argv[1:] or DRIVERS:
        port(name)
